# Generated by Django 5.2.6 on 2025-10-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.CharField(blank=True, default='guntur', max_length=100, null=True),
        ),
    ]
